[package]
name = "frostgate-verifier"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
frostgate-sdk = { path = "../frostgate-sdk" }
sp1-zkvm = { workspace = true }
uuid = { workspace = true }